## ----include = FALSE----------------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

## ----setup, eval = FALSE------------------------------------------------------
# library(formr)
# # Automatically finds your stored keys
# formr_api_authenticate(host = "https://api.formr.org", account = "dashboard") # or your custom URL and account name!

## ----eval = FALSE-------------------------------------------------------------
# # List all active sessions (participants currently in the study)
# active_users <- formr_api_sessions("my-run-name", active = TRUE)
# 
# # List all test sessions (e.g., generated by you)
# test_users <- formr_api_sessions("my-run-name", testing = TRUE)

## ----eval = FALSE-------------------------------------------------------------
# # Inspect a specific user
# user_status <- formr_api_sessions("my-run-name", session_codes = "USER_CODE_123")
# dplyr::glimpse(user_status)

## ----eval = FALSE-------------------------------------------------------------
# # Create a random session code for testing
# new_sessions <- formr_api_create_session("my-run-name", testing = TRUE)
# 
# # Create a session with a specific code (e.g., for a specific ID)
# # Please be sure that your session codes are in an allowed format on your server.
# formr_api_create_session("my-run-name", codes = c("LAB_001", "LAB_002"))

## ----eval = FALSE-------------------------------------------------------------
# # Move user to position 10 (e.g., the next survey)
# formr_api_session_action("my-run-name",
#                      session_codes = "STUCK_USER_CODE",
#                      action = "move_to_position",
#                      position = 10)

## ----eval = FALSE-------------------------------------------------------------
# # Mark a real session as a test session
# formr_api_session_action("my-run-name",
#                      session_codes = "REAL_USER_CODE",
#                      action = "toggle_testing")

## ----eval = FALSE-------------------------------------------------------------
# # End a session
# formr_api_session_action("my-run-name",
#                      session_codes = "WITHDRAWN_USER_Code",
#                      action = "end_external")

