```{r eval=TRUE,echo=FALSE}
if (!exists("indent")) {
	indent = '#' # ugly hack so _regression_summary can be "spun" (variables included via `r ` have to be available)
}
if (exists("testing")) {
	item = 1:10
}
item_info = attributes(item)$item
item_name = item_info$name
item_label = ifelse(is.null(item_info$label), "", item_info$label)
choices = item_info$choices
```

`r indent`## `r item_name` {#`r item_name` .tabset}

`r indent`### Distribution {#`r item_name`_distribution}
```{r}
old_width = knitr::opts_chunk$get("fig.width")
if (is.null(choices) || dplyr::n_distinct(na.omit(item)) > length(choices)) {
	choices = unique(item)
}
new_width = 1.5 * length(choices)
new_width = ifelse(new_width > 20, 20, new_width)
knitr::opts_chunk$set(fig.width = new_width)
```
```{r}
if (dplyr::n_distinct(item) < 20) { 
	dist_plot = ggplot2::ggplot() +
		ggplot2::geom_bar(ggplot2::aes(x = item)) +
		ggplot2::stat_bin(breaks = names(choices)) + 
		ggplot2::ggtitle(item_name, subtitle = item_label) + 
		ggplot2::xlab("Choices")
	
	if (dplyr::n_distinct(item) < 13 && 
			is.numeric(type.convert(names(choices), as.is = T)) && 
			any(names(choices) != unlist(choices))) {
		dist_plot = dist_plot + ggplot2::scale_x_continuous("Choices", breaks = as.numeric(names(choices)), labels = unlist(choices))
	}

	dist_plot
} else {
	cat("More than ", dplyr::n_distinct(item), " unique values, so not shown.")
}
knitr::opts_chunk$set(fig.width = old_width)
```

`r indent`### Summary statistics {#`r item_name`_summary}
```{r}
pander::pander(skimr::skim_v(item))
```

`r indent`### Item {#`r item_name`_item}

```{r}
item_info$label_parsed = item_info$choices = item_info$choice_list = item_info$study_id = item_info$id = NULL
pander::pander(as.data.frame(t(item_info)))
```



`r indent`#### Choices {#`r item_name`_choices}
```{r}
if (!is.null(choices) && length(choices) < 20) {
	pander::pander(choices)
}
```

