---
title: "Codebook example diary"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
pander::panderOptions("table.split.table", Inf)
```


## Load
```{r echo=FALSE}
source("/Volumes/jet/Beziehungsdynamiken/.password.R")
```
```{r}
library(formr)
library(dplyr)
```
```{r cache=TRUE}
formr_connect(email = credentials$user, password = credentials$password, host = credentials$host)
formr_results("Taeglicher_Fragebogen_1", host = credentials$host, quiet = T) -> diary
formr_items("Taeglicher_Fragebogen_1", host = credentials$host) -> diary_items
diary = diary %>% select(session, session_id, modified, created, ended, menstruation_1, menstruation_2, menstruation_3, desirability_partner, NARQ_admiration_1, NARQ_admiration_2, NARQ_admiration_3, NARQ_rivalry_1, NARQ_rivalry_2, NARQ_rivalry_3, NARQ_admiration, NARQ_rivalry)
diary$expired = NA
rm(credentials)
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
theme_set(theme_bw())
```

```{r}
codebook(diary)
```


## Items
```{r}
DT::datatable(dplyr::select(as.data.frame(diary_items), -choice_list, -id, -study_id, -index), rownames = FALSE, filter = "top", extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    pageLength = 200
  )) 
```

